
name: Build TCosmetic
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: { java-version: '21', distribution: 'temurin' }
      - run: chmod +x gradlew
      - run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with: { name: TCosmetic-Build, path: build/libs/ }
